import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WornHub - Audit Logs",
  description: "Generated by create next app",
};

export default function AuditLogsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
